import './db_test';
import './metadata_test';
import './initializer_test';
import './mapper_test';
import './adapter_test';
import './misc_test';
import './viewMapper_test';
import './cached/cached_test';
import "./drop_test";