import './db_test';
import './users_test';
import './metadata_test';
import './initializer_test';
import './mapper_test';
import './adapter_test';
import './misc_test';
import './db/viewMapper_test';
import './cached/cached_test';